# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48a36c8efb3e298080a2b22de6da9f4d73e714df8077370c0573396d3fe65a3ae34915c6fb5e85e31cc4e7ae86f6d3ea284f158c99c1a8b1ff114801f8658c40

test:
  secret_key_base: 48ca2f3d23fb47be5854cd2ca17d66cd0dbcb1977bd88a2d36383d7378d7bf90c606e9b02e77cd70b4c42903c10dbffaac186dd09ccd4879155ebca92466cc68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
